package org.flymars.devtools.midas.report;

import org.flymars.devtools.midas.config.ConfigManager;
import org.flymars.devtools.midas.config.PluginConfig;
import org.flymars.devtools.midas.data.WeeklyReport;

import java.time.format.DateTimeFormatter;

/**
 * Template for generating reports in various formats
 */
public class ReportTemplate {
    private static final DateTimeFormatter DATE_FORMATTER_ZH = DateTimeFormatter.ofPattern("yyyy年MM月dd日");
    private static final DateTimeFormatter DATE_FORMATTER_EN = DateTimeFormatter.ofPattern("MMM dd, yyyy");

    /**
     * Generate markdown report
     */
    public static String generateMarkdown(WeeklyReport report, ConfigManager config) {
        PluginConfig.ReportLanguage language = config.getReportLanguage();
        boolean isEnglish = language == PluginConfig.ReportLanguage.ENGLISH;

        StringBuilder md = new StringBuilder();

        // Header
        DateTimeFormatter formatter = isEnglish ? DATE_FORMATTER_EN : DATE_FORMATTER_ZH;

        if (isEnglish) {
            md.append(String.format("# Weekly Development Report - %s to %s\n\n",
                    report.getWeekStart().format(formatter),
                    report.getWeekEnd().format(formatter)));
        } else {
            md.append(String.format("# 开发周报 - %s 至 %s\n\n",
                    report.getWeekStart().format(formatter),
                    report.getWeekEnd().format(formatter)));
        }

        // Main work content (from AI)
        if (report.getSummary() != null && !report.getSummary().isEmpty()) {
            if (isEnglish) {
                md.append("## 💡 Main Work Content\n\n");
            } else {
                md.append("## 💡 主要工作内容\n\n");
            }
            md.append(report.getSummary());
            md.append("\n\n");
        }

        // Technical highlights
        if (report.getTechnicalHighlights() != null && !report.getTechnicalHighlights().isEmpty()) {
            if (isEnglish) {
                md.append("## 🔍 Technical Highlights\n\n");
            } else {
                md.append("## 🔍 技术要点\n\n");
            }
            md.append(report.getTechnicalHighlights());
            md.append("\n\n");
        }

        // Problems and solutions
        if (report.getProblemsAndSolutions() != null && !report.getProblemsAndSolutions().isEmpty()) {
            if (isEnglish) {
                md.append("## ⚠️ Problems & Solutions\n\n");
            } else {
                md.append("## ⚠️ 问题与解决方案\n\n");
            }
            md.append(report.getProblemsAndSolutions());
            md.append("\n\n");
        }

        // Next week plans
        if (report.getNextWeekPlans() != null && !report.getNextWeekPlans().isEmpty()) {
            if (isEnglish) {
                md.append("## 🎯 Next Week Plans\n\n");
            } else {
                md.append("## 🎯 下周计划\n\n");
            }
            md.append(report.getNextWeekPlans());
            md.append("\n");
        }

        // Footer
        md.append("\n---\n");

        if (isEnglish) {
            md.append("\n---\n");
            md.append("\n📢 **This report is automatically generated by [Midas](https://github.com/ZhaoRuidong/Midas) IntelliJ plugin**\n");
            md.append("\nMidas is an IntelliJ IDEA plugin that helps you:\n");
            md.append("- 📊 Automatically track Git commit records\n");
            md.append("- 🤖 Generate professional weekly reports with AI\n");
            md.append("- 📧 Support email sending and scheduled reminders\n");
            md.append("\n✨ Making weekly report generation simpler and improving work efficiency!\n");
        } else {
            md.append("\n---\n");
            md.append("\n📢 **本报告由 [Midas](https://github.com/ZhaoRuidong/Midas) IntelliJ 插件自动生成**\n");
            md.append("\nMidas 是一款 IntelliJ IDEA 插件，能够：\n");
            md.append("- 📊 自动追踪 Git 提交记录\n");
            md.append("- 🤖 基于 AI 生成专业的周报内容\n");
            md.append("- 📧 支持邮件发送与定时提醒\n");
            md.append("\n✨ 让周报生成更简单，提高工作效率！\n");
        }

        return md.toString();
    }

    /**
     * Generate HTML report
     */
    public static String generateHTML(WeeklyReport report, ConfigManager config) {
        PluginConfig.ReportLanguage language = config.getReportLanguage();
        boolean isEnglish = language == PluginConfig.ReportLanguage.ENGLISH;

        StringBuilder html = new StringBuilder();

        html.append("<!DOCTYPE html>\n");

        if (isEnglish) {
            html.append("<html lang=\"en\">\n");
            html.append("<head>\n");
            html.append("    <meta charset=\"UTF-8\">\n");
            html.append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
            html.append("    <title>Weekly Development Report</title>\n");
        } else {
            html.append("<html lang=\"zh-CN\">\n");
            html.append("<head>\n");
            html.append("    <meta charset=\"UTF-8\">\n");
            html.append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
            html.append("    <title>开发周报</title>\n");
        }

        html.append("    <style>\n");
        html.append(getBaseCSS());
        html.append("    </style>\n");
        html.append("</head>\n");
        html.append("<body>\n");

        html.append("    <div class=\"container\">\n");

        // Header
        DateTimeFormatter formatter = isEnglish ? DATE_FORMATTER_EN : DATE_FORMATTER_ZH;

        if (isEnglish) {
            html.append(String.format("        <h1>Weekly Development Report - %s to %s</h1>\n\n",
                    report.getWeekStart().format(formatter),
                    report.getWeekEnd().format(formatter)));
        } else {
            html.append(String.format("        <h1>开发周报 - %s 至 %s</h1>\n\n",
                    report.getWeekStart().format(formatter),
                    report.getWeekEnd().format(formatter)));
        }

        // Main content
        if (report.getSummary() != null && !report.getSummary().isEmpty()) {
            if (isEnglish) {
                html.append("        <h2>💡 Main Work Content</h2>\n");
            } else {
                html.append("        <h2>💡 主要工作内容</h2>\n");
            }
            html.append("        <div class=\"content\">").append(markdownToHTML(report.getSummary())).append("</div>\n");
        }

        // Technical highlights
        if (report.getTechnicalHighlights() != null && !report.getTechnicalHighlights().isEmpty()) {
            if (isEnglish) {
                html.append("        <h2>🔍 Technical Highlights</h2>\n");
            } else {
                html.append("        <h2>🔍 技术要点</h2>\n");
            }
            html.append("        <div class=\"content\">").append(markdownToHTML(report.getTechnicalHighlights())).append("</div>\n");
        }

        // Problems
        if (report.getProblemsAndSolutions() != null && !report.getProblemsAndSolutions().isEmpty()) {
            if (isEnglish) {
                html.append("        <h2>⚠️ Problems & Solutions</h2>\n");
            } else {
                html.append("        <h2>⚠️ 问题与解决方案</h2>\n");
            }
            html.append("        <div class=\"content\">").append(markdownToHTML(report.getProblemsAndSolutions())).append("</div>\n");
        }

        // Next week
        if (report.getNextWeekPlans() != null && !report.getNextWeekPlans().isEmpty()) {
            if (isEnglish) {
                html.append("        <h2>🎯 Next Week Plans</h2>\n");
            } else {
                html.append("        <h2>🎯 下周计划</h2>\n");
            }
            html.append("        <div class=\"content\">").append(markdownToHTML(report.getNextWeekPlans())).append("</div>\n");
        }

        // Footer
        html.append("        <hr>\n");
        html.append("        <footer>\n");

        html.append("            <div class=\"plugin-promo\">\n");

        if (isEnglish) {
            html.append("                <p>📢 <strong>This report is automatically generated by <a href=\"https://github.com/ZhaoRuidong/Midas\" target=\"_blank\">Midas</a> IntelliJ plugin</strong></p>\n");
            html.append("                <p>Midas is an IntelliJ IDEA plugin that helps you:</p>\n");
            html.append("                <ul>\n");
            html.append("                    <li>📊 Automatically track Git commit records</li>\n");
            html.append("                    <li>🤖 Generate professional weekly reports with AI</li>\n");
            html.append("                    <li>📧 Support email sending and scheduled reminders</li>\n");
            html.append("                </ul>\n");
            html.append("                <p>✨ Making weekly report generation simpler and improving work efficiency!</p>\n");
        } else {
            html.append("                <p>📢 <strong>本报告由 <a href=\"https://github.com/ZhaoRuidong/Midas\" target=\"_blank\">Midas</a> IntelliJ 插件自动生成</strong></p>\n");
            html.append("                <p>Midas 是一款 IntelliJ IDEA 插件，能够：</p>\n");
            html.append("                <ul>\n");
            html.append("                    <li>📊 自动追踪 Git 提交记录</li>\n");
            html.append("                    <li>🤖 基于 AI 生成专业的周报内容</li>\n");
            html.append("                    <li>📧 支持邮件发送与定时提醒</li>\n");
            html.append("                </ul>\n");
            html.append("                <p>✨ 让周报生成更简单，提高工作效率！</p>\n");
        }

        html.append("            </div>\n");
        html.append("        </footer>\n");

        html.append("    </div>\n");
        html.append("</body>\n");
        html.append("</html>\n");

        return html.toString();
    }

    /**
     * Get base CSS for HTML reports
     */
    public static String getBaseCSS() {
        return """
                body {
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                    max-width: 900px;
                    margin: 0 auto;
                    padding: 20px;
                    background-color: #f5f5f5;
                }

                .container {
                    background: white;
                    padding: 30px;
                    border-radius: 8px;
                    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                }

                h1 {
                    color: #2c3e50;
                    border-bottom: 3px solid #3498db;
                    padding-bottom: 10px;
                }

                h2 {
                    color: #34495e;
                    margin-top: 30px;
                    border-left: 4px solid #3498db;
                    padding-left: 10px;
                }

                .content {
                    background: #f8f9fa;
                    padding: 15px;
                    border-radius: 5px;
                    margin: 10px 0;
                }

                hr {
                    border: none;
                    border-top: 1px solid #ddd;
                    margin: 30px 0;
                }

                footer {
                    text-align: center;
                    color: #7f8c8d;
                    font-size: 14px;
                }

                .plugin-promo {
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    padding: 20px;
                    border-radius: 8px;
                    margin-top: 20px;
                    color: white;
                }

                .plugin-promo p {
                    margin: 8px 0;
                }

                .plugin-promo a {
                    color: #ffd700;
                    text-decoration: none;
                    font-weight: bold;
                }

                .plugin-promo a:hover {
                    text-decoration: underline;
                }

                .plugin-promo ul {
                    text-align: left;
                    display: inline-block;
                    margin: 10px 0;
                    padding-left: 20px;
                }

                .plugin-promo li {
                    margin: 5px 0;
                }

                ul, ol {
                    padding-left: 20px;
                }

                li {
                    margin: 5px 0;
                }
                """;
    }

    /**
     * Simple markdown to HTML converter
     */
    private static String markdownToHTML(String markdown) {
        if (markdown == null) {
            return "";
        }

        String html = markdown
                .replaceAll("### (.*)", "<h3>$1</h3>")
                .replaceAll("## (.*)", "<h2>$1</h2>")
                .replaceAll("- (.*)", "<li>$1</li>")
                .replaceAll("\\*\\*(.*?)\\*\\*", "<strong>$1</strong>")
                .replaceAll("\\*(.*?)\\*", "<em>$1</em>");

        // Wrap lists
        if (html.contains("<li>")) {
            html = "<ul>" + html + "</ul>";
        }

        // Convert line breaks
        html = html.replaceAll("\n", "<br>\n");

        return html;
    }

    private static String capitalize(String str) {
        if (str == null || str.isEmpty()) {
            return str;
        }
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }
}
