package org.flymars.devtools.midas.report;

import org.flymars.devtools.midas.config.ConfigManager;
import org.flymars.devtools.midas.config.PluginConfig;
import org.flymars.devtools.midas.data.WeeklyReport;
import org.flymars.devtools.midas.ui.component.MarkdownPreviewPanel;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Template for generating reports in various formats
 */
public class ReportTemplate {
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("yyyy年MM月dd日");
    private static final Pattern FOOTER_SEPARATOR_PATTERN = Pattern.compile("(?m)^\\s*---\\s*$");

    /**
     * Generate markdown report
     */
    public static String generateMarkdown(WeeklyReport report, ConfigManager config) {
        PluginConfig.ReportLanguage language = config.getReportLanguage();
        boolean isEnglish = language == PluginConfig.ReportLanguage.ENGLISH;

        StringBuilder md = new StringBuilder();

        // 主要工作内容由 AI 生成，使用标准 Markdown 空行保证预览换行稳定。
        if (hasMarkdownContent(report.getSummary())) {
            if (isEnglish) {
                md.append("## Main Work Content\n\n");
            } else {
                md.append("## 主要工作内容\n\n");
            }
            md.append(normalizeMarkdownBlock(report.getSummary()));
            md.append("\n\n");
        }

        // 下周计划同样保留段落间空行，避免列表和标题在预览中粘连。
        if (hasMarkdownContent(report.getNextWeekPlans())) {
            if (isEnglish) {
                md.append("## Next Week Plans\n\n");
            } else {
                md.append("## 下周计划\n\n");
            }
            md.append(normalizeMarkdownBlock(report.getNextWeekPlans()));
            md.append("\n\n");
        }

        // 页脚前只保留一个分隔线。
        md.append("---\n");

        if (isEnglish) {
            md.append("\n📢 **This report is automatically generated by [Midas](https://github.com/ZhaoRuidong/Midas) IntelliJ plugin**\n");
            md.append("\nMidas is an IntelliJ IDEA plugin that helps you:\n");
            md.append("- 📊 Automatically track Git commit records\n");
            md.append("- 🤖 Generate professional weekly reports with AI\n");
            md.append("- 📧 Support email sending and scheduled reminders\n");
            md.append("\n✨ Making weekly report generation simpler and improving work efficiency!\n");
        } else {
            md.append("\n📢 **本报告由 [Midas](https://github.com/ZhaoRuidong/Midas) IntelliJ 插件自动生成**\n");
            md.append("\nMidas 是一款 IntelliJ IDEA 插件，能够：\n");
            md.append("- 📊 自动追踪 Git 提交记录\n");
            md.append("- 🤖 基于 AI 生成专业的周报内容\n");
            md.append("- 📧 支持邮件发送与定时提醒\n");
            md.append("\n✨ 让周报生成更简单，提高工作效率！\n");
        }

        return md.toString();
    }

    /**
     * 生成邮件发送使用的 HTML 周报。
     */
    public static String generateHTML(WeeklyReport report, ConfigManager config) {
        PluginConfig.ReportLanguage language = config.getReportLanguage();
        boolean isEnglish = language == PluginConfig.ReportLanguage.ENGLISH;

        StringBuilder body = new StringBuilder();

        // 正文由 AI Markdown 渲染而来，外层邮件样式负责提供稳定的版式和间距。
        if (hasMarkdownContent(report.getSummary())) {
            body.append(buildContentSection(
                    isEnglish ? "Main Work Content" : "主要工作内容",
                    markdownToHTML(normalizeMarkdownBlock(report.getSummary()))
            ));
        }

        if (hasMarkdownContent(report.getNextWeekPlans())) {
            if (!body.isEmpty()) {
                body.append(buildDivider());
            }
            body.append(buildContentSection(
                    isEnglish ? "Next Week Plans" : "下周计划",
                    markdownToHTML(normalizeMarkdownBlock(report.getNextWeekPlans()))
            ));
        }

        return buildEmailShell(
                isEnglish,
                isEnglish ? "Weekly Development Report" : "开发周报",
                formatDateRange(report, isEnglish),
                body.toString(),
                buildPluginFooter(isEnglish)
        );
    }

    /**
     * 将预览弹窗中编辑后的 Markdown 转为新版邮件 HTML。
     */
    public static String generateHTMLFromMarkdown(String markdown, WeeklyReport report, ConfigManager config) {
        PluginConfig.ReportLanguage language = config.getReportLanguage();
        boolean isEnglish = language == PluginConfig.ReportLanguage.ENGLISH;
        String contentMarkdown = stripGeneratedFooter(markdown);
        String contentHtml = """
                <tr>
                    <td style="padding: 34px 38px 12px;">
                        <div class="midas-content" style="color: #334155; font-size: 15px; line-height: 1.85;">
                %s
                        </div>
                    </td>
                </tr>
                """.formatted(markdownToHTML(contentMarkdown));

        return buildEmailShell(
                isEnglish,
                isEnglish ? "Weekly Development Report" : "开发周报",
                formatDateRange(report, isEnglish),
                contentHtml,
                buildPluginFooter(isEnglish)
        );
    }

    /**
     * 组装完整邮件外壳，使用 table 和内联样式提升邮件客户端兼容性。
     */
    private static String buildEmailShell(boolean isEnglish, String title, String subtitle, String bodyRows, String footerRows) {
        String language = isEnglish ? "en" : "zh-CN";
        String brandLabel = isEnglish ? "Midas Weekly Report" : "Midas Weekly Report";

        StringBuilder html = new StringBuilder();
        html.append("<!DOCTYPE html>\n");
        html.append("<html lang=\"").append(language).append("\">\n");
        html.append("<head>\n");
        html.append("    <meta charset=\"UTF-8\">\n");
        html.append("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
        html.append("    <title>").append(escapeHtml(title)).append("</title>\n");
        html.append("    <style>\n");
        html.append(getBaseCSS());
        html.append("    </style>\n");
        html.append("</head>\n");
        html.append("<body style=\"margin: 0; padding: 0; background: #eef2f7; color: #1f2937; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Microsoft YaHei', Arial, sans-serif;\">\n");
        html.append("    <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"border-collapse: collapse; background: #eef2f7;\">\n");
        html.append("        <tr>\n");
        html.append("            <td align=\"center\" style=\"padding: 28px 12px;\">\n");
        html.append("                <table role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"width: 100%; max-width: 760px; border-collapse: collapse; background: #ffffff; border-radius: 14px; overflow: hidden; box-shadow: 0 14px 36px rgba(15, 23, 42, 0.10);\">\n");
        html.append("                    <tr>\n");
        html.append("                        <td style=\"padding: 34px 38px 30px; background: #0f172a;\">\n");
        html.append("                            <div style=\"font-size: 13px; line-height: 1.4; color: #93c5fd; font-weight: 700; letter-spacing: 0; margin-bottom: 12px;\">").append(brandLabel).append("</div>\n");
        html.append("                            <h1 style=\"margin: 0; color: #ffffff; font-size: 30px; line-height: 1.25; font-weight: 800; letter-spacing: 0;\">").append(escapeHtml(title)).append("</h1>\n");
        html.append("                            <p style=\"margin: 12px 0 0; color: #cbd5e1; font-size: 15px; line-height: 1.7;\">").append(escapeHtml(subtitle)).append("</p>\n");
        html.append("                        </td>\n");
        html.append("                    </tr>\n");
        html.append(bodyRows);
        html.append(footerRows);
        html.append("                </table>\n");
        html.append("            </td>\n");
        html.append("        </tr>\n");
        html.append("    </table>\n");
        html.append("</body>\n");
        html.append("</html>\n");

        return html.toString();
    }

    /**
     * 构建正文分区，标题固定内联样式，内容交给 Markdown 渲染结果展示。
     */
    private static String buildContentSection(String title, String contentHtml) {
        return """
                <tr>
                    <td style="padding: 34px 38px 10px;">
                        <h2 style="margin: 0 0 18px; color: #0f172a; font-size: 21px; line-height: 1.35; font-weight: 800; letter-spacing: 0;">%s</h2>
                        <div class="midas-content" style="color: #334155; font-size: 15px; line-height: 1.85;">
                %s
                        </div>
                    </td>
                </tr>
                """.formatted(escapeHtml(title), contentHtml);
    }

    /**
     * 构建邮件中两个内容区之间的细分隔线。
     */
    private static String buildDivider() {
        return """
                <tr>
                    <td style="padding: 24px 38px 8px;">
                        <div style="height: 1px; line-height: 1px; background: #e2e8f0;">&nbsp;</div>
                    </td>
                </tr>
                """;
    }

    /**
     * 构建 Midas 插件签名区，避免 Markdown 页脚在邮件里变成松散列表。
     */
    private static String buildPluginFooter(boolean isEnglish) {
        if (isEnglish) {
            return """
                    <tr>
                        <td style="padding: 24px 38px 34px;">
                            <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px;">
                                <tr>
                                    <td style="padding: 22px 24px;">
                                        <p style="margin: 0 0 12px; color: #0f172a; font-size: 16px; line-height: 1.6; font-weight: 800;">📢 This report is automatically generated by <a href="https://github.com/ZhaoRuidong/Midas" style="color: #2563eb; text-decoration: none; font-weight: 800;">Midas IntelliJ plugin</a></p>
                                        <p style="margin: 0 0 10px; color: #475569; font-size: 14px; line-height: 1.75;">Midas tracks Git commits, generates weekly reports with AI, and supports email delivery with scheduled reminders.</p>
                                        <p style="margin: 0; color: #64748b; font-size: 13px; line-height: 1.7;">✨ Making weekly report generation simpler and improving work efficiency!</p>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                    """;
        }

        return """
                <tr>
                    <td style="padding: 24px 38px 34px;">
                        <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px;">
                            <tr>
                                <td style="padding: 22px 24px;">
                                    <p style="margin: 0 0 12px; color: #0f172a; font-size: 16px; line-height: 1.6; font-weight: 800;">📢 本报告由 <a href="https://github.com/ZhaoRuidong/Midas" style="color: #2563eb; text-decoration: none; font-weight: 800;">Midas IntelliJ 插件</a> 自动生成</p>
                                    <p style="margin: 0 0 10px; color: #475569; font-size: 14px; line-height: 1.75;">Midas 是一款 IntelliJ IDEA 插件，能够自动追踪 Git 提交记录，基于 AI 生成专业周报，并支持邮件发送与定时提醒。</p>
                                    <p style="margin: 0; color: #64748b; font-size: 13px; line-height: 1.7;">✨ 让周报生成更简单，提高工作效率！</p>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
                """;
    }

    /**
     * 获取 HTML 周报的基础样式，主要用于 Markdown 渲染出的正文标签。
     */
    public static String getBaseCSS() {
        return """
                body {
                    margin: 0;
                    padding: 0;
                    background: #eef2f7;
                    color: #1f2937;
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Microsoft YaHei', Arial, sans-serif;
                }

                .container {
                    max-width: 760px;
                    margin: 24px auto;
                    padding: 34px 38px;
                    background: #ffffff;
                    border-radius: 14px;
                    box-shadow: 0 14px 36px rgba(15, 23, 42, 0.10);
                }

                .midas-content h1,
                .container h1 {
                    margin: 0 0 18px;
                    color: #0f172a;
                    font-size: 24px;
                    line-height: 1.35;
                    font-weight: 800;
                    letter-spacing: 0;
                }

                .midas-content h2,
                .container h2 {
                    margin: 24px 0 14px;
                    color: #0f172a;
                    font-size: 20px;
                    line-height: 1.35;
                    font-weight: 800;
                    letter-spacing: 0;
                }

                .midas-content h3,
                .container h3 {
                    display: inline-block;
                    margin: 18px 0 10px;
                    padding: 5px 11px;
                    border-radius: 999px;
                    background: #dbeafe;
                    color: #1d4ed8;
                    font-size: 13px;
                    line-height: 1.4;
                    font-weight: 700;
                }

                .midas-content p,
                .container p {
                    margin: 0 0 10px;
                    color: #334155;
                    font-size: 15px;
                    line-height: 1.85;
                }

                .midas-content ul,
                .midas-content ol,
                .container ul,
                .container ol {
                    margin: 0 0 12px;
                    padding: 0 0 0 22px;
                    color: #334155;
                    font-size: 15px;
                    line-height: 1.85;
                }

                .midas-content li,
                .container li {
                    margin: 0 0 10px;
                }

                .midas-content a,
                .container a {
                    color: #2563eb;
                    text-decoration: none;
                    font-weight: 700;
                }

                .midas-content hr,
                .container hr {
                    border: none;
                    border-top: 1px solid #e2e8f0;
                    margin: 24px 0;
                }

                .content {
                    color: #334155;
                    font-size: 15px;
                    line-height: 1.85;
                }

                .plugin-promo {
                    background: #f8fafc;
                    border: 1px solid #e2e8f0;
                    border-radius: 12px;
                    padding: 22px 24px;
                    margin-top: 20px;
                }

                .plugin-promo p {
                    margin: 0 0 10px;
                    color: #475569;
                    font-size: 14px;
                    line-height: 1.75;
                }

                .plugin-promo a {
                    color: #2563eb;
                    text-decoration: none;
                    font-weight: 800;
                }

                @media screen and (max-width: 640px) {
                    .container {
                        margin: 0;
                        border-radius: 0;
                        padding: 24px 20px;
                    }
                }
                """;
    }

    private static String markdownToHTML(String markdown) {
        return MarkdownPreviewPanel.renderMarkdownToHtml(markdown);
    }

    /**
     * 规范化 AI 返回的 Markdown 片段，避免前后多余空白影响标题和列表渲染。
     */
    private static String normalizeMarkdownBlock(String markdown) {
        return markdown == null ? "" : markdown.strip();
    }

    /**
     * 去掉 Markdown 中已有的 Midas 页脚，避免编辑后发送时重复出现插件介绍。
     */
    private static String stripGeneratedFooter(String markdown) {
        String normalized = normalizeMarkdownBlock(markdown);
        Matcher matcher = FOOTER_SEPARATOR_PATTERN.matcher(normalized);
        int lastSeparatorStart = -1;
        while (matcher.find()) {
            lastSeparatorStart = matcher.start();
        }
        if (lastSeparatorStart < 0) {
            return normalized;
        }
        return normalized.substring(0, lastSeparatorStart).strip();
    }

    /**
     * 格式化周报日期范围。
     */
    private static String formatDateRange(WeeklyReport report, boolean isEnglish) {
        LocalDate weekStart = report == null ? null : report.getWeekStart();
        LocalDate weekEnd = report == null ? null : report.getWeekEnd();
        if (weekStart == null || weekEnd == null) {
            return isEnglish ? "Current reporting period" : "当前周报周期";
        }
        if (isEnglish) {
            return weekStart + " to " + weekEnd;
        }
        return DATE_FORMATTER.format(weekStart) + " 至 " + DATE_FORMATTER.format(weekEnd);
    }

    /**
     * 转义少量动态文本，避免标题和日期中的特殊字符破坏 HTML。
     */
    private static String escapeHtml(String text) {
        if (text == null) {
            return "";
        }
        return text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;");
    }

    /**
     * 判断 Markdown 片段是否包含可展示内容。
     */
    private static boolean hasMarkdownContent(String markdown) {
        return markdown != null && !markdown.isBlank();
    }
}
